sports = []
sports.append("Tennis")
sports.insert(0, "Football")
sports.insert(2, "Basketball")
print(sports)
sports.pop()
print(sports)
sports.append("Golf")
print(sports)
sports.sort()
print(sports)
sports.sort(reverse=True)
print(sports)
print(sorted(sports))
print(len(sports))
