guests = ["messi", "ronaldo", "maradonna"]
print(f"Hello {guests[0]}, you are invited to dinner!")
print(f"Hello {guests[1]}, you are invited to dinner!")
print(f"Hello {guests[2]}, you are invited to dinner!")
print(f"Unfortunately, {guests[2]} could not make it to dinner.")
guests.pop()
guests.append("pele")
print("Here are the new guests")
print(f"Hello {guests[0]}, you are invited to dinner!")
print(f"Hello {guests[1]}, you are invited to dinner!")
print(f"Hello {guests[2]}, you are invited to dinner!")

print("\n WE FOUND A BIGGER TABLE")
guests.insert(0, "Cuau")
guests.insert(2, "Jared")
guests.append("Pirlo")
print(f"Hello {guests[0]}, you are invited to dinner!")
print(f"Hello {guests[1]}, you are invited to dinner!")
print(f"Hello {guests[2]}, you are invited to dinner!")
print(f"Hello {guests[3]}, you are invited to dinner!")
print(f"Hello {guests[4]}, you are invited to dinner!")
print(f"Hello {guests[5]}, you are invited to dinner!")

print("\n Now only two persons can be invited")
guests.pop()
guests.pop()
guests.pop()
guests.pop()
print(f"{guests[0]}, you are still invited.")
print(f"{guests[1]}, you are still invited.")
print(guests)
del guests[0]
del guests[0]
print(guests)
